# Generated by Django 4.2.4 on 2023-08-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('with_medicine_userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('W', '여성(Woman)'), ('O', '기타(Other)'), ('M', '남성(Man)')], max_length=1, null=True, verbose_name='성별'),
        ),
    ]
