# Generated by Django 4.2.4 on 2023-08-17 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('with_medicine_free', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='free_comment',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='l_posts_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='free_board',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='free_board',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='l_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
