# Generated by Django 4.2.4 on 2023-08-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speciallist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciallist_name', models.CharField(max_length=50)),
                ('speciallist_type', models.CharField(max_length=50)),
                ('speciallist_hospital', models.TextField()),
            ],
        ),
    ]
